Create and use admin password
This uses the new container that takes the admin username
and password from environment variables.
Some notes:
- It puts the password in a file in the plugin directory.
- It creates a new password if this file does not exist,
  when starting the plugin with jenkins:start.
- It does not provide linking currently, will add soon.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,10 @@
 #!/bin/bash
+set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
+
+source "$(dirname "$0")/config"
 
 docker pull rhub/rocker-jenkins
 
+mkdir -p "$PLUGIN_DATA_ROOT" || \
+    echo "Failed to create $PLUGIN_DATA_ROOT directory"
+chown dokku:dokku "$PLUGIN_DATA_ROOT"
